function importAll(r) {
  let images = {};
  r.keys().map((item, index) => {
    images[item.replace("./", "")] = r(item);
  });
  return images;
}

const images = importAll(
  require.context("../assets", false, /\.(png|jpe?g|svg)$/)
);

export const dwarka_categories = ["Chotas", "Bada", "Sides", "Sweet Dish"];

export const dwarka = [
  {
    id: "m1",
    name: "Gucchi And Girda",
    description: "Haak, whey yakhni, kohlrabi, poppy seed girda",
    price: 635,
    image: images["gucchigirda.png"],
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Chotas",
  },
  {
    id: "m2",
    name: "Ghee Roast Seekh",
    description: "Pear and kohlrabi koshambir",
    price: 535,
    image: images["roastseekh.png"],
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Chotas",
  },
  {
    id: "m3",
    name: "Chicken Sukka",
    description: "Charred coconut masala, kokum, pickled shallots",
    price: 550,
    image: images["chickensukka.png"],
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Chotas",
  },
  {
    id: "m4",
    name: "Khasi Pork Tacol",
    description: "Grilled sesame pork belly, Naga chili salsa, rice bhakri",
    price: 550,
    image: images["porktaco.png"],
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Chotas",
  },
  {
    id: "m5",
    name: "Baigan Chokha",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 395,
    image: images["banglachicken.png"],
    imageV: images["veg.png"],
    veg: "nonveg",
    category: "Chotas",
  },
  {
    id: "m6",
    name: "Millet Haleem",
    description: "Lamba pao, puffed millets, crispy lotus root",
    price: 425,
    image: images["millethaleem.png"],
    imageV: images["veg.png"],
    veg: "nonveg",
    category: "Chotas",
  },
  {
    id: "m7",
    name: "Kodava Mushroom (Vegan)",
    description: "Mixed mushrooms, dark toasted spices, kachampuli",
    price: 635,
    image: images["kmushroom.png"],
    imageV: images["nonveg.png"],
    veg: "veg",
    category: "Bada",
  },
  {
    id: "m8",
    name: "Petha And Mirch Salan",
    description: "Peanut-sesame seed curry, malai paneer, masala chili crisp",
    price: 595,
    image: images["pmsalan.png"],
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Bada",
  },
  {
    id: "m9",
    name: "Fish Pulimunchi (Gluten Free)",
    description: "Tamarind-chili masala, baby methi & radish salad",
    price: 775,
    image: images["fishpulimunchi.png"],
    imageV: images["veg.png"],
    veg: "nonveg",
    category: "Bada",
  },
  {
    id: "m10",
    name: "Dak Bangla Chicken",
    description: "Spicy caramelized onion curry, soft cooked egg",
    price: 695,
    image: images["banglachicken.png"],
    imageV: images["nonveg.png"],
    veg: "veg",
    category: "Bada",
  },
  {
    id: "m11",
    name: "Malai Kofta",
    description: "Masala aloo - straciatella kofta, pumpkin curry, chili oil",
    price: 665,
    image: images["malaikofta.png"],
    imageV: images["veg.png"],
    veg: "veg",
    category: "Bada",
  },
  {
    id: "m12",
    name: "Garlic Sourdough Naan",
    description: "Sprinkled with lal mirch, sesame & kalonji",
    price: 165,
    image: images["garlicnaan.png"],
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Sides",
  },
  {
    id: "m13",
    name: "Malabar Paratha",
    description:
      "This flat bread is the perfect complement to any spicy curry dish.",
    price: 135,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sides",
  },
  {
    id: "m14",
    name: "Steamed Rice",
    description: " ",
    price: 165,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sides",
  },
  {
    id: "m15",
    name: "Maska Pao",
    description:
      "The bun is a soft bread, while maska is homemade makhan or butter.",
    price: 110,
    image: "",
    veg: "veg",
    imageV: images["veg.png"],
    category: "Sides",
  },
  {
    id: "m16",
    name: "Pao No Maska",
    description: "Normal bun with a soft bread",
    price: 110,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sides",
  },
  {
    id: "m17",
    name: "Akela Bread",
    description:
      "An ode to 2020s most popular quarantine dessert - banana bread, canteen style!",
    price: 485,
    image: images["akelabread.png"],
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Sweet Dish",
  },
  {
    id: "m18",
    name: "Coffee Rasgulla Sundae",
    description:
      "Rum-mascarpone ganache, salted caramel coffee cream, toasted almond brittle",
    price: 510,
    image: images["coffeerasgullasundae.png"],
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sweet Dish",
  },
];
