export const pourpure_categories = ["Chotas", "Bada", "Sides", "Sweet Dish"];

export const pourpure = [
  {
    id: "m1",
    name: "Gucchi And Girda",
    description: "",
    price: 635,
    image: "",
    veg: true,
    category: "Chotas",
  },
  {
    id: "m2",
    name: "Ghee Roast Seekh",
    description: "",
    price: 535,
    image: "",
    veg: false,
    category: "Chotas",
  },
  {
    id: "m3",
    name: "Chicken Sukka",
    description: "",
    price: 550,
    image: "",
    veg: false,
    category: "Chotas",
  },
  {
    id: "m4",
    name: "Khasi Pork Tacol",
    description: "",
    price: 550,
    image: "",
    veg: false,
    category: "Chotas",
  },
  {
    id: "m5",
    name: "Baigan Chokha",
    description: "",
    price: 395,
    image: "",
    veg: true,
    category: "Chotas",
  },
  {
    id: "m6",
    name: "Millet Haleem",
    description: "",
    price: 425,
    image: "",
    veg: true,
    category: "Chotas",
  },
  {
    id: "m7",
    name: "Kodava Mushroom (Vegan)",
    description: "",
    price: 635,
    image: "",
    veg: true,
    category: "Bada",
  },
  {
    id: "m8",
    name: "Petha And Mirch Salan",
    description: "",
    price: 595,
    image: "",
    veg: true,
    category: "Bada",
  },
  {
    id: "m9",
    name: "Fish Pulimunchi (Gluten Free)",
    description: "",
    price: 775,
    image: "",
    veg: false,
    category: "Bada",
  },
  {
    id: "m10",
    name: "Dak Bangla Chicken",
    description: "",
    price: 695,
    image: "",
    veg: false,
    category: "Bada",
  },
  {
    id: "m11",
    name: "Malai Kofta",
    description: "",
    price: 665,
    image: "",
    veg: true,
    category: "Bada",
  },
  {
    id: "m12",
    name: "Garlic Sourdough Naan",
    description: "",
    price: 165,
    image: "",
    veg: true,
    category: "Sides",
  },
  {
    id: "m13",
    name: "Malabar Paratha",
    description: "",
    price: 135,
    image: "",
    veg: true,
    category: "Sides",
  },
  {
    id: "m14",
    name: "Steamed Rice",
    description: " ",
    price: 165,
    image: "",
    veg: true,
    category: "Sides",
  },
  {
    id: "m15",
    name: "Maska Pao",
    description: "",
    price: 110,
    image: "",
    veg: true,
    category: "Sides",
  },
  {
    id: "m16",
    name: "Pao No Maska",
    description: "",
    price: 110,
    image: "",
    veg: true,
    category: "Sides",
  },
  {
    id: "m17",
    name: "Akela Bread",
    description: "",
    price: 485,
    image: "",
    veg: false,
    category: "Sweet Dish",
  },
  {
    id: "m18",
    name: "Coffee Rasgulla Sundae",
    description: "",
    price: 510,
    image: "",
    veg: true,
    category: "Sweet Dish",
  },
];
