/** @format */

function importAll(r) {
  let images = {};
  r.keys().map((item, index) => {
    images[item.replace("./", "")] = r(item);
  });
  return images;
}

const images = importAll(
  require.context("../assets", false, /\.(png|jpe?g|svg)$/)
);

export const redindies_categories = [
  "Chinese Starters",
  "Mexican Starters",
  "Continental Soups",
  "Thai Soups",
  "Chinese Soups",
  "Baltic Side Walks",
  "Insalata (Salad)",
  "Mexican Delights",
  "Enchiladas",
  "Baked Hot Potatoes",
  "Pizza",
  "Pizza Toppings",
  "Sizzlers",
  "Italian Delights",
  "Lasagne",
  "Pasta",
  "Chinese Main Course",
  "Rice & Noodles",
  "Chop Suey",
  "Desserts",
  "Mocktails",
  "Milk Shakes",
];

export const redindies = [
  {
    id: "m1",
    name: "Lemon Coriander Soup",
    description: "Haak, whey yakhni, kohlrabi, poppy seed girda",
    price: 155,
    image:
      "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=393&q=80",

    imageV: images["veg.png"],
    veg: "veg",
    category: "Continental Soups",
  },
  {
    id: "m2",
    name: "Minestrone Soup",
    description: "Pear and kohlrabi koshambir",
    price: 190,
    image:
      "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",

    imageV: images["veg.png"],
    veg: "veg",
    category: "Continental Soups",
  },
  {
    id: "m3",
    name: "Cream of French Onion Soup",
    description: "Charred coconut masala, kokum, pickled shallots",
    price: 185,
    image: "",

    imageV: images["veg.png"],
    veg: "veg",
    category: "Continental Soups",
  },
  {
    id: "m4",
    name: "Cream of Broccoli & Asparagus Soup",
    description: "Grilled sesame pork belly, Naga chili salsa, rice bhakri",
    price: 215,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Continental Soups",
  },
  {
    id: "m5",
    name: "Tom Yum Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 190,
    image:
      "https://images.unsplash.com/photo-1478749485505-2a903a729c63?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Thai Soups",
  },
  {
    id: "m6",
    name: "Thukpa Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 210,
    image:
      "https://images.unsplash.com/photo-1652288282543-0fc019cfc457?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Thai Soups",
  },
  {
    id: "m7",
    name: "Veg. Clear Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 135,
    image:
      "https://images.unsplash.com/photo-1478749485505-2a903a729c63?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m8",
    name: "Veg. Noodles Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 135,
    image:
      "https://images.unsplash.com/photo-1555126634-323283e090fa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bm9vZGxlJTIwc291cHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m9",
    name: "Cream of Spinach",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 160,
    image:
      "https://images.unsplash.com/photo-1626200949840-179d3e52f7fd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8Y3JlYW0lMjBvZiUyMHNwaW5hY2h8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m10",
    name: "Veg. Wanton Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 185,
    image:
      "https://images.unsplash.com/photo-1506267594256-7667b0040d31?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHdhbnRvbiUyMHNvdXB8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m11",
    name: "Cream of Tomato Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 180,
    image:
      "https://images.unsplash.com/photo-1620418025834-f4379baf1de9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dG9tYXRvJTIwc291cHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m12",
    name: "Cream of Mushroom Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 185,
    image:
      "https://images.unsplash.com/photo-1624633431700-b0912297c13a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8bXVzaHJvb20lMjBzb3VwfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m13",
    name: "Veg. Sweet Corn Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 180,
    image:
      "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c3dlZXQlMjBjb3JuJTIwc291cHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m14",
    name: "Hot & Sour Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 195,
    image:
      "https://images.unsplash.com/photo-1641595573308-8964aa5d6a21?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aG90JTIwJTI2JTIwc291ciUyMHNvdXB8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m15",
    name: "Veg. Sweet Corn Mushroom Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 195,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m16",
    name: "Manchow Soup",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 215,
    image:
      "https://images.unsplash.com/photo-1470324161839-ce2bb6fa6bc3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWFuY2hvdyUyMHNvdXB8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Soups",
  },
  {
    id: "m17",
    name: "Chinese Bhel",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 195,
    image:
      "https://images.unsplash.com/photo-1641642399335-6867075ee7db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YmhlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m18",
    name: "Crispy Spring Roll",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 215,
    image:
      "https://images.unsplash.com/photo-1577859584099-38d38a4aacb5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y3Jpc3B5JTIwc3ByaW5nJTIwcm9sbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m19",
    name: "Veg Manchurian Dry",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 215,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m20",
    name: "Mushroom Schezwan Dry",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 255,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m21",
    name: "Schezwan Fingers",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 255,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m22",
    name: "Oriental Finger Roll",
    description: "Exotic Veggies wrapped in finger shaped rolls",
    price: 265,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m23",
    name: "Paneer in Salt & Pepper",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 310,
    image:
      "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cGFuZWVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m24",
    name: "Crispy Veg in Salt & Pepper",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 245,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m25",
    name: "Paneer Chilly Dry",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 295,
    image:
      "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHBhbmVlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m26",
    name: "Crispy Vegetables",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 285,
    image:
      "https://images.unsplash.com/photo-1654458804670-2f4f26ab3154?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGNyaXNweSUyMHZlZ2V0YWJsZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m27",
    name: "Malaysian Cottage Cheese",
    description:
      "Chunks of Paneer sauteed with bell peppers & crushed peanuts in Red Sauce",
    price: 330,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m28",
    name: "Stir Fried Vegetables",
    description: "Exotic Diced veggies tossed in olive oil & herbs",
    price: 315,
    image:
      "https://images.unsplash.com/photo-1641919062245-98117fd30791?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGZyaWVkJTIwdmVnZXRhYmxlc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m29",
    name: "Red Indian Chef's Special",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 325,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m30",
    name: "Crispy Veg in Honey Ginger Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 295,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m31",
    name: "Crispy Paneer in Honey Ginger Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 315,
    image:
      "https://images.unsplash.com/photo-1627662235824-d9f447830c76?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Y3Jpc3B5JTIwcGFuZWVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m32",
    name: "Veg Balls In Black Bean Dry",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 245,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m33",
    name: "Veg Balls In Schezwan Dry",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 235,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m34",
    name: "Paneer In Black Bean Dry",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 325,
    image:
      "https://images.unsplash.com/photo-1589647363585-f4a7d3877b10?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cGFuZWVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m35",
    name: "Paneer In Schezwan Dry",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 310,
    image:
      "https://images.unsplash.com/photo-1551881192-002e02ad3d87?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cGFuZWVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m36",
    name: "French Fries In Schezwan Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 255,
    image:
      "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8ZnJlbmNoJTIwZnJpZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Starters",
  },
  {
    id: "m37",
    name: "Tortilla Chips with Salsa Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 205,
    image:
      "https://images.unsplash.com/photo-1564758565426-1a503a83f5c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dG9ydGlsbGElMjBjaGlwc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m38",
    name: "Onion Rings",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 185,
    image:
      "https://images.unsplash.com/photo-1625938146369-adc83368bda7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8T25pb24lMjBSaW5nc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m39",
    name: "Capsicum Rings",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 195,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m40",
    name: "Cajun Potatoes",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 245,
    image:
      "https://images.unsplash.com/photo-1548869205-3b74ad80e605?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8Y2FqdW4lMjBwb3RhdG9lc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m41",
    name: "Baby Corn Fingers",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 235,
    image:
      "https://images.unsplash.com/photo-1632992468854-7b1d83134bc4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFieSUyMGNvcm58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m42",
    name: "Veg. Cheese Quesadilla",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 285,
    image:
      "https://images.unsplash.com/photo-1628838233717-be047a0b54fb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hlZXNlJTIwcXVlc2FkaWxsYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m43",
    name: "Mushroom Cheese Quesadilla",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 285,
    image:
      "https://images.unsplash.com/photo-1647545401800-bd8f77e670ed?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Y2hlZXNlJTIwcXVlc2FkaWxsYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m44",
    name: "Golden Corn Cheese Balls",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 275,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m45",
    name: "Mexican Beans Tacos",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 255,
    image:
      "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dGFjb3N8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m46",
    name: "Assorted Vegetables Tacos",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 295,
    image:
      "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dGFjb3N8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m47",
    name: "Nachos with Cheese Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 295,
    image:
      "https://images.unsplash.com/photo-1582169296194-e4d644c48063?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bmFjaG9zfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m48",
    name: "Nachos with Am Corn & Cheese Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 305,
    image:
      "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bmFjaG9zfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m49",
    name: "Nachos with Refried Beans & Cheese Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 315,
    image:
      "https://images.unsplash.com/photo-1619604107557-b5321217aee7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8bmFjaG9zfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m50",
    name: "Mexican Platter (Regular)",
    description:
      "A Combination of Nachos, Cheese Corn Balls, Baby Corn Fingers, Onion & Capsicum rings",
    price: 325,
    image:
      "https://images.unsplash.com/photo-1651994410607-bf6810a0bb35?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8bWV4aWNhbiUyMHBsYXR0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m51",
    name: "Mexican Platter (Large)",
    description:
      "A Combination of Nachos, Cheese Corn Balls, Baby Corn Fingers, Onion & Capsicum rings",
    price: 495,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m52",
    name: "Extra Cheese Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 80,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m53",
    name: "Extra Beans / Am. Corn",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 60,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Starters",
  },
  {
    id: "m54",
    name: "Bread Butter (3 Slice)",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 55,
    image:
      "https://images.unsplash.com/photo-1619095956510-24c12e2c4b9a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGJyZWFkJTIwYnV0dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m55",
    name: "French Fries",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 95,
    image:
      "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZnJlbmNoJTIwZnJpZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m56",
    name: "Potato Wedges",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 125,
    image:
      "https://images.unsplash.com/photo-1623238913973-21e45cced554?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cG90YXRvJTIwd2VkZ2VzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m57",
    name: "Potato Nuggets",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 115,
    image:
      "https://images.unsplash.com/photo-1627662055487-551888db3aa8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cG90YXRvJTIwbnVnZ2V0c3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m58",
    name: "Banana Finger Fries",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 110,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m59",
    name: "Banana Fries in Pepper Sauce",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 185,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m60",
    name: "Red Indian Special Burger",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 145,
    image:
      "https://images.unsplash.com/photo-1530554764233-e79e16c91d08?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8c3BlY2lhbCUyMGJ1cmdlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m61",
    name: "Vegetable Sandwich",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 65,
    image:
      "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2FuZHdpY2h8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m62",
    name: "Veg. Cheese Sandwich",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 95,
    image:
      "https://images.unsplash.com/photo-1528736235302-52922df5c122?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fHNhbmR3aWNofGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m63",
    name: "Veg. Grilled / Toast Sandwich",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 95,
    image:
      "https://images.unsplash.com/photo-1445093498563-4ba5fecf1bc7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fHRvYXN0JTIwc2FuZHdpY2h8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m64",
    name: "Veg. Cheese Grilled Sandwich",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 125,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m65",
    name: "Veg. Club Sandwich",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 135,
    image:
      "https://images.unsplash.com/photo-1529907789406-c4651fc0b919?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHRvYXN0JTIwc2FuZHdpY2h8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m66",
    name: "Pepper Chilly Cheese Toast",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 185,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m67",
    name: "Italian Garlic Bread",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 155,
    image:
      "https://images.unsplash.com/photo-1593527270723-834c53a3fed4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Z2FybGljJTIwYnJlYWR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m68",
    name: "Cheesy Italian Garlic Bread",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 205,
    image:
      "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Z2FybGljJTIwYnJlYWR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m69",
    name: "Italian Jain Bread",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 155,
    image:
      "https://images.unsplash.com/photo-1556008531-57e6eefc7be4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8Z2FybGljJTIwYnJlYWR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m70",
    name: "Italian Jain Cheese Bread",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 205,
    image:
      "https://images.unsplash.com/photo-1532452960476-f234eee8bd71?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGdhcmxpYyUyMGJyZWFkfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baltic Side Walks",
  },
  {
    id: "m71",
    name: "Bruschetta",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 295,
    image:
      "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YnJ1c2NoZXR0YXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Baltic Side Walks",
  },
  {
    id: "m72",
    name: "Garden Fresh Green Salad",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 175,
    image:
      "https://images.unsplash.com/photo-1514537099923-4c0fc7c73161?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Z3JlZW4lMjBzYWxhZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Insalata (Salad)",
  },
  {
    id: "m73",
    name: "Mexican Salad",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 215,
    image:
      "https://images.unsplash.com/photo-1608032077018-c9aad9565d29?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Z3JlZW4lMjBzYWxhZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Insalata (Salad)",
  },
  {
    id: "m74",
    name: "Russian Salad",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 235,
    image:
      "https://images.unsplash.com/photo-1610903122389-3674aafb17a5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGdyZWVuJTIwc2FsYWR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Insalata (Salad)",
  },
  {
    id: "m75",
    name: "Exotic Salad",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 285,
    image:
      "https://images.unsplash.com/photo-1546793665-c74683f339c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fGdyZWVuJTIwc2FsYWR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Insalata (Salad)",
  },
  {
    id: "m76",
    name: "Greek Salad",
    description:
      "Diced Veggies,Lettuce Leaves dressed in salad oil with herbs & garnished with feta Cheese",
    price: 295,
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGdyZWVuJTIwc2FsYWR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Insalata (Salad)",
  },
  {
    id: "m77",
    name: "Caesar Salad",
    description:
      "Sundried Tomatoes, Croutors, Lollo Rosso, Ice berg etc. tossed in home made caesar dressing with herbs and parmesan cheese",
    price: 305,
    image:
      "https://images.unsplash.com/photo-1623489254660-db5b367881d9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGdyZWVuJTIwc2FsYWR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Insalata (Salad)",
  },
  {
    id: "m78",
    name: "Mexican Rice",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 345,
    image:
      "https://images.unsplash.com/photo-1641238255912-f939644442f4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fG1leGljYW4lMjByaWNlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Delights",
  },
  {
    id: "m79",
    name: "Creamy Macaroni Mexicana",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 335,
    image:
      "https://images.unsplash.com/photo-1612892010343-983bfd063dc5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8bWFjYXJvbml8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mexican Delights",
  },
  {
    id: "m80",
    name: "Golden Corn Enchiladas",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 265,
    image:
      "https://images.unsplash.com/photo-1570461226513-e08b58a52c53?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y29ybiUyMGVuY2hpbGFkYXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Enchiladas",
  },
  {
    id: "m81",
    name: "Mushroom & Cheese Enchiladas",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 285,
    image:
      "https://images.unsplash.com/photo-1637002058113-02cfabfc51b5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8ZW5jaGlsYWRhc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Enchiladas",
  },
  {
    id: "m82",
    name: "Jain Enchiladas",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 295,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Enchiladas",
  },
  {
    id: "m83",
    name: "Beans & Cheese Enchiladas",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 275,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Enchiladas",
  },
  {
    id: "m85",
    name: "Red Indian Special Enchiladas",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 325,
    image:
      "https://images.unsplash.com/photo-1648071598153-428215dce7bb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8ZW5jaGlsYWRhc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Enchiladas",
  },
  {
    id: "m86",
    name: "Creamed Roasted Garlic & Cheese",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 245,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baked Hot Potatoes",
  },
  {
    id: "m87",
    name: "Creamed Roasted Capsicum & Cheese",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 255,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baked Hot Potatoes",
  },
  {
    id: "m88",
    name: "Creamed Mushroom & Cheese",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 275,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baked Hot Potatoes",
  },
  {
    id: "m89",
    name: "Mexican Red Beans & Cheese",
    description: "Sattu papdi, tomato oil, pickled chillies",
    price: 285,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Baked Hot Potatoes",
  },
  {
    id: "m90",
    name: "Italian Cheese Pizza",
    description: "Italian Tomato Puree with Italian herbs & Mozzarella Cheese",
    price: 245,
    image:
      "https://images.unsplash.com/photo-1620374645498-af6bd681a0bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Y2hlZXNlJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },
  {
    id: "m91",
    name: "Standard Vegetable Pizza",
    description: "Onion & Capsicum",
    price: 305,
    image:
      "https://images.unsplash.com/photo-1651307443944-2f4dc148fb5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8dmVnZXRhYmxlJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },
  {
    id: "m92",
    name: "The Margherita",
    description: "Basil & Tomato Slices",
    price: 305,
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8bWFyZ2hlcml0YSUyMHBpenphfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },
  {
    id: "m93",
    name: "Green House",
    description: "Sp. Onion, Capsicum, Green Peas & Green Chilly",
    price: 325,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },
  {
    id: "m94",
    name: "Jain Cheese Pizza",
    description: "Basil & Tomato Slices",
    price: 355,
    image:
      "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Y2hlZXNlJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },
  {
    id: "m95",
    name: "Veg. Delight",
    description: "Roasted Pepper, Tomato Cubes & Corn, Roasted Garlic & Herbs",
    price: 345,
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8Y2hlZXNlJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m96",
    name: "The Mediterranean",
    description:
      "Spicy Cauliflower with Tomato Cubes, Jalapeno & Roasted Pepper",
    price: 325,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pizza",
  },

  {
    id: "m97",
    name: "Mix Vegetable Pizza",
    description: "Onion, Capsicum & Tomatoes",
    price: 325,
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHZlZyUyMHBpenphfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m98",
    name: "Olive Garden",
    description: "Black & Green Olives & Roasted Garlic & Herbs",
    price: 375,
    image:
      "https://images.unsplash.com/photo-1458642849426-cfb724f15ef7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fHZlZyUyMHBpenphfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m99",
    name: "Veggie Lovers Pizza",
    description: "Mixed Vegetables with Spices",
    price: 345,
    image:
      "https://images.unsplash.com/photo-1555072956-7758afb20e8f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fHZlZyUyMHBpenphfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m100",
    name: "Farmer's Choice",
    description: "Onion, Capsicum, Oregano, Tomatoes & Corn",
    price: 375,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m101",
    name: "B.B.Q. Mushroom Pizza",
    description: "B.B.Q. Mushroom with Sp. Onion, Capsicum",
    price: 375,
    image:
      "https://images.unsplash.com/photo-1604917869287-3ae73c77e227?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8dmVnJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m102",
    name: "Mac & Cheese Pizza",
    description: "Cheese Macaroni Pasta topped with Black & Green Olives",
    price: 385,
    image:
      "https://images.unsplash.com/photo-1555072956-7758afb20e8f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8bWFjJTIwJTI2JTIwY2hlZXNlJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m103",
    name: "B.B.Q. Paneer Pizza",
    description: "B.B.Q. Paneer Pizza",
    price: 395,
    image:
      "https://images.unsplash.com/photo-1596458397260-255807e979f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGFuZWVyJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m104",
    name: "Exotica",
    description:
      "Slices of Red Yellow Capsicum with Black & Green Olives & Bits of Am. Corn",
    price: 385,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m105",
    name: "Paneer Tikka",
    description: "Tandoori Paneer with Olives & Spring Onion",
    price: 395,
    image:
      "https://images.unsplash.com/photo-1573821663912-569905455b1c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cGFuZWVyJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m106",
    name: "Red Indian Special",
    description:
      "Mushroom, Jalapeno, Olives, Sundried Tomatoes Red & Yellow Capsicum",
    price: 415,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m107",
    name: "Wild Country Classic Veg",
    description:
      "Slices of Red & Yellow Capsicum with Sundried Tomatoes & Jalapenos",
    price: 385,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },
  {
    id: "m108",
    name: "Florentine",
    description: "Chunks of Tandoori Paneer, Spring Onion, Spinach & Capsicum",
    price: 395,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pizza",
  },
  {
    id: "m109",
    name: "Tropocal Pizza",
    description:
      "Broccoli, Cottage Cheese, Zuccini, Bell Peppers, Olives & Baby Corn",
    price: 425,
    image:
      "https://images.unsplash.com/photo-1528137871618-79d2761e3fd5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHRyb3BpY2FsJTIwcGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza",
  },

  {
    id: "m110",
    name: "Fresh Tomato Slices / Cubes",
    description: "",
    price: 40,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza Toppings",
  },
  {
    id: "m111",
    name: "Sp. Onion",
    description: "",
    price: 40,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza Toppings",
  },

  {
    id: "m112",
    name: "Spinach",
    description: "",
    price: 40,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza Toppings",
  },

  {
    id: "m113",
    name: "Garlic",
    description: "",
    price: 40,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza Toppings",
  },

  {
    id: "m114",
    name: "Jalapeno",
    description: "",
    price: 40,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza Toppings",
  },
  {
    id: "m115",
    name: "Green Peas",
    description: "",
    price: 40,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza Toppings",
  },
  {
    id: "m116",
    name: "Capsicum",
    description: "",
    price: 40,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pizza Toppings",
  },

  {
    id: "m117",
    name: "Saucy Garlic",
    description: "",
    price: 445,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m118",
    name: "Veggie Pepper",
    description: "",
    price: 455,
    image:
      "https://im.whatshot.in/img/2019/Jan/best-sizzlers-in-mumbai-whats-hot-mumbai-1548746174.jpg",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m119",
    name: "Smashy Potatoes",
    description: "",
    price: 475,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m120",
    name: "Veg. Satellite",
    description: "Garden fresh veggies with mushroom, Fresh cream & Cheese",
    price: 495,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },
  {
    id: "m121",
    name: "Veg. Sizzler with Baked Beans, Noodles & Garlic Sauce",
    description: "",
    price: 485,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m122",
    name: "Hearts on Fire",
    description: "",
    price: 495,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m123",
    name: "Jain Special Sizzlers",
    description: "",
    price: 485,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m124",
    name: "Veg. Spaghetti & Cheese Sauce",
    description: "",
    price: 385,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m125",
    name: "Paneer Shaslik",
    description: "",
    price: 495,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m126",
    name: "Exotic Veg. Sizzler",
    description:
      "Veggies such as Broccoli, Red cabbage, Bell peppers, Babycorn etc.",
    price: 530,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m127",
    name: "Paneer Shaslik",
    description: "",
    price: 495,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m128",
    name: "Veg. Sizzler in B.B.Q. Paneer",
    description: "",
    price: 525,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m129",
    name: "Veg. Sizzler in B.B.Q. Paneer",
    description:
      "Diced veggies with cubes of Cottage cheese, Zucchini, Babycorn, Fries etc.",
    price: 525,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m130",
    name: "Veg Sizzler with Beans Sprout",
    description: "",
    price: 515,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },

  {
    id: "m131",
    name: "Red Indian Special Sizzlers",
    description:
      "Garden fresh veggies with Mushroom, Babycorn, Paneer & Cheese",
    price: 545,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },
  {
    id: "m132",
    name: "Extra Cutlet Veg / Panner / Jain",
    description: "",
    price: 90,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },
  {
    id: "m133",
    name: "Extra Smashy Potatoes",
    description: "",
    price: 515,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Sizzlers",
  },
  {
    id: "m134",
    name: "Veg Sizzler with Beans Sprout",
    description:
      "Cauliflower sauteed with Garlic, Onion & Celery, Cooked in Spicy Tomato Herb Sauce & Served on a bed of Pasta with Cheese Sauce",
    price: 395,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Italian Delights",
  },
  {
    id: "m135",
    name: "Risotto Indiana",
    description:
      "A Traditional Italian Rice Cooked in Olive Oil & Flavoured with Italian Herbs & served with Creamy Rich Bechamel Sauce",
    price: 405,
    image:
      "https://images.unsplash.com/photo-1621341258668-b2bf005a9f97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cmlzb3R0b3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Italian Delights",
  },
  {
    id: "m136",
    name: "Crespelle Amalfi",
    description:
      "Pancakes flavoured with Italian herbs, Stuffed with Creamy Spinach & Am. Corn pebbles Topped with Fresh Mushroom Cheese Sauce",
    price: 515,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Italian Delights",
  },

  {
    id: "m137",
    name: "Crespelle Verde",
    description:
      "Exotic Veggies such as Broccoli, Zucchini, Bell Peppers & Baby Corn wrapped in Pancakes flavoured with herbs in Cheese Paprika Sauce",
    price: 435,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Italian Delights",
  },
  {
    id: "m138",
    name: "Gnoochi Della Chef",
    description:
      "Potato Gnoochi, stuffed with Spinach & Golden Am. Corn Pebbles Tossed in Creamy Tomato Basil Sauce",
    price: 435,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Italian Delights",
  },

  {
    id: "m139",
    name: "Con Funghi Trifolati",
    description:
      "Fresh Baby Corn & Mushroom Cooked in Creamy Tomato Paprika Basil Sauce served with warm Farmers Bread",
    price: 515,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Italian Delights",
  },
  {
    id: "m140",
    name: "Legume Al Forno",
    description: "",
    price: 515,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Italian Delights",
  },

  {
    id: "m141",
    name: "Napoletana",
    description: "Fresh Basil & Tomato Sauce & Topped with Cheese",
    price: 385,
    image:
      "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGFzYWduYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Lasagne",
  },
  {
    id: "m142",
    name: "Corn & Spinach",
    description:
      "Sauteed Corn & Spinach in Cheese filling & Topped with Olives",
    price: 445,
    image:
      "https://images.unsplash.com/photo-1619895092538-128341789043?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bGFzYWduYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Lasagne",
  },
  {
    id: "m143",
    name: "Primavera",
    description:
      "Assorted Garden Fresh Green Vegetables & Am. Corn in Cheese filling Topped with Marinara Sauce",
    price: 515,
    image:
      "https://images.unsplash.com/photo-1629115916087-7e8c114a24ed?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8bGFzYWduYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Lasagne",
  },

  {
    id: "m144",
    name: "Cannelonial Forno",
    description:
      "Rolled Pasta dressed with stuffed Spinach, Herbs & Cheese Sauce",
    price: 315,
    image:
      "https://images.unsplash.com/photo-1633436374961-09b92742047b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8bGFzYWduYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Lasagne",
  },

  {
    id: "m144",
    name: "Basilico",
    description:
      "Pasta Sauteed in rich tomato & fresh basil sauce with Italian herbs & spices",
    price: 345,
    image:
      "https://images.unsplash.com/photo-1592774912353-72756004ecbb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFzaWxpY298ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pasta",
  },
  {
    id: "m145",
    name: "Piscaute",
    description: "A warm pasta with spicy tomato & chilly sauce",
    price: 395,
    image:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cGFzdGF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pasta",
  },
  {
    id: "m146",
    name: "New Berg",
    description:
      "A combination of fresh tomato, bechamel & creamy cheese sauce with basil & paprika",
    price: 425,
    image:
      "https://images.unsplash.com/photo-1608897013039-887f21d8c804?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cGFzdGF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pasta",
  },
  {
    id: "m147",
    name: "Al Formiara",
    description:
      "Macaroni tossed in creamy cheese sauce with a sprinkle of basil tomato sauce flavoured with roasted garlic & pepper",
    price: 315,
    image:
      "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fHBhc3RhfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pasta",
  },
  {
    id: "m148",
    name: "Farfalle Paprika",
    description: "Pasta in rich tomato sauce with vegetables, paprika & cheese",
    price: 375,
    image:
      "https://images.unsplash.com/photo-1599749011927-9a77278bfa61?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHBhc3RhfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pasta",
  },

  {
    id: "m149",
    name: "Sicilana",
    description:
      "Penne Pasta in marinara sauce topped with roasted bell pepper",
    price: 315,
    image:
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHBhc3RhfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pasta",
  },

  {
    id: "m150",
    name: "Spinach in Spaghetti",
    description: "A Classic combination of cheese & spinach sauce",
    price: 365,
    image:
      "https://images.unsplash.com/photo-1546549032-9571cd6b27df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cGFzdGF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pasta",
  },

  {
    id: "m151",
    name: "Spinach in Spaghetti",
    description: "A Classic combination of cheese & spinach sauce",
    price: 365,
    image:
      "https://images.unsplash.com/photo-1611270629569-8b357cb88da9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cGFzdGF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pasta",
  },
  {
    id: "m152",
    name: "Fettuccine Arrabiata",
    description:
      "Spicy Italian tomato sauce, with roasted garlic & Italian herbs with added vegetables",
    price: 435,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pasta",
  },
  {
    id: "m153",
    name: "Pasta in Pesto Sauce",
    description:
      "Spaghetti tossed in fresh basil garlic & parmesan cheese sauce & topped with bell pepper & cherry tomato",
    price: 415,
    image:
      "https://images.unsplash.com/photo-1598866594230-a7c12756260f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cGFzdGF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pasta",
  },
  {
    id: "m154",
    name: "Alfredo",
    description:
      "Pasta in rich fresh cream & cheese sauce, dressed up with olives",
    price: 425,
    image:
      "https://images.unsplash.com/photo-1579684947550-22e945225d9a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fHBhc3RhfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pasta",
  },
  {
    id: "m155",
    name: "Con Funghi Cremia",
    description:
      "A mix of mushroom, babycorn & veggies tossed in creamy cheese sauce",
    price: 415,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pasta",
  },
  {
    id: "m156",
    name: "Agloi Olio",
    description: "Pasta tossed in garlic & herbs with parmesan cheese",
    price: 425,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Pasta",
  },
  {
    id: "m157",
    name: "Extra Vegetables Toppings",
    description: "",
    price: 70,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pasta",
  },
  {
    id: "m158",
    name: "Extra Cheese Toppings",
    description: "",
    price: 65,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Pasta",
  },
  {
    id: "m159",
    name: "Veg. Manchurian",
    description: "",
    price: 235,
    image: "",
    category: "Chinese Main Course",
  },
  {
    id: "m169",
    name: "Sweet & Sour Vegetables",
    description: "",
    price: 235,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course",
  },
  {
    id: "m170",
    name: "Veg. Balls In Green Chilly Sauce",
    description: "",
    price: 235,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course ",
  },
  {
    id: "m171",
    name: "Veg. Schezwan",
    description: "",
    price: 255,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course",
  },
  {
    id: "m172",
    name: "Veg. Balls In Garlic (Hot Garlic)",
    description: "",
    price: 265,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course",
  },
  {
    id: "m173",
    name: "Mushroom (Your choice of sauce)",
    description:
      "Chilly/Manchurian/Garlic/Ginger/   Hong Kong/Schezwan/Black Bean",
    price: 295,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course",
  },
  {
    id: "m174",
    name: "Baby Corn (Your choice of sauce)",
    description:
      "Chilly/Manchurian/Garlic/Ginger/   Hong Kong/Schezwan/Black Bean",
    price: 295,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course",
  },
  {
    id: "m175",
    name: "Paneer (Your choice of sauce)",
    description:
      "Chilly/Manchurian/Garlic/Ginger/   Hong Kong/Schezwan/Black Bean",
    price: 335,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course ",
  },
  {
    id: "m176",
    name: "Red Indian Special Vegetables",
    description:
      "Diced Vegetables with Paneer, Baby Corn & Mushroom in Red Sauce",
    price: 345,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Chinese Main Course",
  },

  {
    id: "m177",
    name: "Green Thai Curry",
    description:
      "Chilly/Manchurian/Garlic/Ginger/   Hong Kong/Schezwan/Black Bean",
    price: 305,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Chinese Main Course",
  },

  {
    id: "m178",
    name: "Paneer (Your choice of sauce)",
    description:
      "Chilly/Manchurian/Garlic/Ginger/   Hong Kong/Schezwan/Black Bean",
    price: 335,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course",
  },

  {
    id: "m179",
    name: "Paneer (Your choice of sauce)",
    description:
      "Chilly/Manchurian/Garlic/Ginger/   Hong Kong/Schezwan/Black Bean",
    price: 335,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chinese Main Course",
  },

  {
    id: "m180",
    name: "Steamed Rice",
    description: "",
    price: 105,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },

  {
    id: "m181",
    name: "Spring Onion Fried Rice",
    description: "",
    price: 185,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },

  {
    id: "m182",
    name: "Hakka Noodles",
    description: "",
    price: 225,
    image:
      "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bm9vZGxlc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },

  {
    id: "m183",
    name: "Veg. Fried Rice",
    description: "",
    price: 235,
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8ZnJpZWQlMjByaWNlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },

  {
    id: "m184",
    name: "Mushroom Fried Rice",
    description: "",
    price: 255,
    image:
      "https://images.unsplash.com/photo-1512058533999-106ee01bf777?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGZyaWVkJTIwcmljZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },

  {
    id: "m185",
    name: "Schezwan Noodles",
    description: "",
    price: 335,
    image:
      "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8ZnJpZWQlMjByaWNlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },

  {
    id: "m186",
    name: "Schezwan Rice",
    description: "",
    price: 135,
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZnJpZWQlMjByaWNlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },
  {
    id: "m187",
    name: "Combination Rice",
    description: "",
    price: 305,
    image:
      "https://images.unsplash.com/photo-1582450925753-18f06f902014?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGZyaWVkJTIwcmljZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },
  {
    id: "m188",
    name: "Combination Schezwan Rice",
    description: "",
    price: 135,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Rice & Noodles",
  },
  {
    id: "m190",
    name: "Singapore Rice",
    description: "",
    price: 235,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Rice & Noodles",
  },

  {
    id: "m191",
    name: "American Chop Suey",
    description: "",
    price: 235,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Chop Suey",
  },
  {
    id: "m192",
    name: "Chinese Chop Suey",
    description: "",
    price: 235,
    image: "",
    imageV: images["nonveg.png"],
    veg: "nonveg",
    category: "Chop Suey",
  },
  {
    id: "m193",
    name: "Triple Schezwan",
    description: "",
    price: 235,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chop Suey",
  },
  {
    id: "m194",
    name: "Pot Rice",
    description: "",
    price: 235,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Chop Suey",
  },

  {
    id: "m195",
    name: "Vanilla Ice Cream",
    description: "",
    price: 435,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Desserts",
  },
  {
    id: "m196",
    name: "Strawberry Crush Ice Cream",
    description: "",
    price: 205,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Desserts",
  },
  {
    id: "m197",
    name: "Vanilla with Hot Chocolate Sauce",
    description: "",
    price: 205,
    image:
      "https://images.unsplash.com/photo-1639744092433-0e98ca50d5fc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8dmFuaWxsYSUyMHdpdGglMjBob3QlMjBjaG9jb2xhdGV8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Desserts",
  },
  {
    id: "m198",
    name: "Caramel Custard",
    description: "",
    price: 105,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Desserts",
  },
  {
    id: "m199",
    name: "Sizzling Brownie with Vanilla / Strawberry crush (Single)",
    description: "",
    price: 235,
    image:
      "https://images.unsplash.com/photo-1639744093238-d12f04cf5950?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c2l6emxpbmclMjBicm93bmllfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Desserts",
  },
  {
    id: "m200",
    name: "Sizzling Brownie with Vanilla / Strawberry crush (Double)",
    description: "",
    price: 335,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Desserts",
  },

  {
    id: "m202",
    name: "Blue Lagoon",
    description: "",
    price: 130,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mocktails",
  },
  {
    id: "m204",
    name: "Kiwi Punch",
    description: "",
    price: 295,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mocktails",
  },
  {
    id: "m205",
    name: "Kiwi Cooler",
    description: "",
    price: 135,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mocktails",
  },
  {
    id: "m206",
    name: "Virgin Mojito",
    description: "",
    price: 165,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mocktails",
  },
  {
    id: "m207",
    name: "Black Current Mojito",
    description: "",
    price: 245,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Mocktails",
  },
  {
    id: "m208",
    name: "Banana",
    description: "",
    price: 115,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Milk Shakes",
  },
  {
    id: "m209",
    name: "Chocolate",
    description: "",
    price: 295,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Milk Shakes",
  },
  {
    id: "m210",
    name: "Blue Berry",
    description: "",
    price: 205,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Milk Shakes",
  },
  {
    id: "m211",
    name: "Strawberry Crush Ice Cream Shake",
    description: "",
    price: 105,
    image: "",
    imageV: images["veg.png"],
    veg: "veg",
    category: "Milk Shakes",
  },
];
